/*
 * @Author: dushuai
 * @Date: 2024-04-15 17:10:01
 * @LastEditors: dushuai
 * @LastEditTime: 2024-04-18 17:39:34
 * @description: layout
 */
import type { Metadata } from "next";
import "../asstes/styles/globals.css";
import { Suspense } from "react";
import { NavigationEvents } from "@/components/NavigationEvents";
import Loading from "./loading";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_TITLE,
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body>
        {children}

        <Suspense fallback={<Loading />}>
          <NavigationEvents />
        </Suspense>
      </body>
    </html>
  )
}
