/*
 * @Author: dushuai
 * @Date: 2024-04-15 17:10:01
 * @LastEditors: dushuai
 * @LastEditTime: 2024-04-16 17:32:39
 * @description: layout
 */
import type { Metadata } from "next";
import "../asstes/styles/globals.css";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
