/*
 * @Author: dushuai
 * @Date: 2024-04-16 14:49:32
 * @LastEditors: dushuai
 * @LastEditTime: 2024-04-16 16:33:47
 * @description: 心平气和
 */
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next · User",
  description: "Generated by create next app",
}

export default function UserLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <>
      <div>user header</div>

      <>
        {children}
      </>

      <div>user footer</div>
    </>
  )
}
